### ISSUE TITLE
How can I use OR expression in breakpoints?

### ISSUE THREAD

**Issue by jdjuan** [eduardoboucas/include-media#132] opened 2016-06-03 17:12 UTC
Hello Include-media Team!,

I am just wondering how can I achieve something like this: 

`@include media("<=900px OR height<700px"){ ... }`

The following way works like an AND: but I need an OR

`@include media("<=900px",  "height<700px"){ ... }`

Today I use 2 different `@include`, and it works. But I couldn't figure out how to achieve the above.

**Comment by HugoGiraudel** [comment] 2016-06-18 12:00
It’s not possible with include-media. Sorry! :)

**Comment by HugoGiraudel** [comment] 2016-06-18 12:08
Possible duplicate of #102.

**Comment by eduardoboucas** [comment] 2016-06-18 16:54
Moving the discussion to #102.

**Closed by eduardoboucas** 2016-06-18 16:54 UTC
